# Site settings
title: Daniel Bahl
description: This page contains links to Daniel's profiles on social media, projects etc.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Bahl
user_description: Coder. Designer. Geek.
user_title: Nerd
email: anon@danielbahl.com
twitter_username: danielbahl
github_username:  danielbahl
gplus_username:  danielbahl

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
