# Permalinks
permalink:           pretty

# Setup
title:               Daniel Bahl
tagline:             Hi! I'm Daniel
url:                 http://danielbahl.com
paginate:            1
baseurl:             "/danielbahl.dk"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daniel Bahl
  url:               https://twitter.com/danielbahl
  email:             me@danielbahl.com

# Custom vars
version:             21.5.0
github:
  repo:              https://github.com/danielbahl/danielbahl.dk/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
